### ISSUE TITLE
Error in Configuring Opensips CLI on Debian - 10

### ISSUE THREAD

**Issue by kaviyarj-28** [OpenSIPS/opensips-cli#104]
Hi
I installed opensips successfully, but during the time of configuring opensips CLI, I get this error.

> root@opensips:~# opensips-cli
Welcome to CLI!
(cli): mi
ERROR: module 'mi' expects the following commands: get_statistics, list_statistics, reset_statistics, uptime, version, pwd, arg, which, ps, kill, log_level, xlog_level, shm_check, cache_store, cache_fetch, cache_remove, event_subscribe, events_list, subscribers_list, raise_event, list_tcp_conns, mem_pkg_dump, mem_shm_dump, mem_rpm_dump, reload_routes, help, list_blacklists, t_uac_dlg, t_uac_cancel, t_hash, t_reply, ul_rm, ul_rm_contact, ul_dump, ul_flush, ul_add, ul_show_contact, ul_sync, ul_cluster_sync

These are the lines I have added in file ~/.opensips-cli.cfg

> [default]
> log_level: WARNING
> prompt_name: cli
> prompt_intro: Welcome to CLI!
> prompt_emptyline_repeat_cmd: False
> history_file: ~/.opensips-cli.history
> history_file_size: 1000
> output_type: pretty-print
> communication_type: fifo
> fifo_file: /tmp/opensips_fifo
> domain: opensips.org

Where did I go wrong. Can anyone help me out to slove this.?

Thanks

**Comment by liviuchircu** [comment]
Hi, @kaviyarj-28!  That is just an error message suggesting that no argument was provided to `mi`, hence the list of possible arguments.  Maybe this message can be given as a "Usage for <mi> command:" type of info message, instead of an error.

Closing for now, cheers!

**Comment by kaviyarj-28** [comment]
Hi,
Now understood. Thanks
