### ISSUE TITLE
No opensips-db_mysql package in yum repo Version 3.X

### ISSUE THREAD

**Issue by YounianC** [OpenSIPS/opensips-cli#105]
according to document:
1. https://github.com/OpenSIPS/opensips-cli/blob/master/docs/INSTALLATION.md
--- "yum install https://yum.opensips.org/3.1/releases/el/7/x86_64/opensips-yum-releases-3.1-6.el7.noarch.rpm"

then i can installed opensips and opensips-cli

2. https://github.com/OpenSIPS/opensips-cli/blob/master/docs/modules/database.md#Examples 
--- "yum install opensips-db_mysql"

but i get "No matches found" for  opensips-db_mysql, 
and i checked yum repo of opensisp : "https://yum.opensips.org/2.4/releases/el/7/x86_64/", i found only 2.4 hava the opensips-db_mysql package.

so what i have to do is  copy the sql script from source code of opensips to the right path which opensips-cli needed, then i can execute "opensips-cli -x database add rtpproxy".

is where a better way to get this done ?
and why there is no opensips-db_mysql anymore?(which i think the best way to install mysql script)

**Comment by NicholasCarr** [comment]
Had same issue, `yum install opensips-db-mysql` worked for us

**Comment by YounianC** [comment]
> 

i still cannot find the package, could you please paste result of `yum repolist` and `yum info opensips-db-mysql` ? thank you !

**Comment by YounianC** [comment]
> Had same issue, `yum install opensips-db-mysql` worked for us

i still cannot find the package, could you please paste result of `yum repolist` and `yum info opensips-db-mysql` ? thank you !

**Comment by NicholasCarr** [comment]
sorry it was `opensips-mysql-module`
```
# yum repolist
Loaded plugins: langpacks
repo id                                                                                         repo name                                                                                                                              status
base-openlogic/7/x86_64                                                                         CentOS-7 - Base (OpenLogic)                                                                                                            10,072
extras-openlogic/7/x86_64                                                                       CentOS-7 - Extras (OpenLogic)                                                                                                             517
updates-openlogic/7/x86_64                                                                      CentOS-7 - Updates (OpenLogic)                                                                                                          4,922
base/7/x86_64                                                                                   CentOS-7 - Base                                                                                                                        10,072
epel/x86_64                                                                                     Extra Packages for Enterprise Linux 7 - x86_64                                                                                         13,771
extras/7/x86_64                                                                                 CentOS-7 - Extras                                                                                                                         515
openlogic/7/x86_64                                                                              CentOS-7 - OpenLogic packages for x86_64                                                                                                   28
opensips/x86_64                                                                                 OpenSIPS - Open Source SIP proxy/server for el7 - x86_64                                                                                  519
opensips-cli                                                                                    OpenSIPS CLI tool - Open Source SIP proxy/server for el7 - x86_64                                                                           4
remi-php74                                                                                      Remi's PHP 7.4 RPM repository for Enterprise Linux 7 - x86_64                                                                             457
remi-safe                                                                                       Safe Remi's RPM repository for Enterprise Linux 7 - x86_64                                                                              5,147
updates/7/x86_64                                                                                CentOS-7 - Updates                                                                                                                      4,886
repolist: 50,910
```

from memory we ran 
```
yum install https://yum.opensips.org/3.2/releases/el/7/x86_64/opensips-yum-releases-3.2-6.el7.noarch.rpm
yum install opensips opensips-cli opensips-mysql-module
```

```
yum info opensips-mysql-module
Loaded plugins: langpacks
Installed Packages
Name        : opensips-mysql-module
Arch        : x86_64
Version     : 3.2.11
Release     : 1.el7
Size        : 145 k
Repo        : installed
From repo   : opensips
Summary     : MySQL database connectivity module for OpenSIPS
URL         : https://opensips.org
License     : GPLv2+
Description : OpenSIPS is a very fast and flexible SIP (RFC3261)
            : server. Written entirely in C, OpenSIPS can handle thousands calls
            : per second even on low-budget hardware.
            : .
            : This package provides the MySQL database driver for OpenSIPS.

```

**Comment by YounianC** [comment]
> sorry it was `opensips-mysql-module`
> 
> ```
> # yum repolist
> Loaded plugins: langpacks
> repo id                                                                                         repo name                                                                                                                              status
> base-openlogic/7/x86_64                                                                         CentOS-7 - Base (OpenLogic)                                                                                                            10,072
> extras-openlogic/7/x86_64                                                                       CentOS-7 - Extras (OpenLogic)                                                                                                             517
> updates-openlogic/7/x86_64                                                                      CentOS-7 - Updates (OpenLogic)                                                                                                          4,922
> base/7/x86_64                                                                                   CentOS-7 - Base                                                                                                                        10,072
> epel/x86_64                                                                                     Extra Packages for Enterprise Linux 7 - x86_64                                                                                         13,771
> extras/7/x86_64                                                                                 CentOS-7 - Extras                                                                                                                         515
> openlogic/7/x86_64                                                                              CentOS-7 - OpenLogic packages for x86_64                                                                                                   28
> opensips/x86_64                                                                                 OpenSIPS - Open Source SIP proxy/server for el7 - x86_64                                                                                  519
> opensips-cli                                                                                    OpenSIPS CLI tool - Open Source SIP proxy/server for el7 - x86_64                                                                           4
> remi-php74                                                                                      Remi's PHP 7.4 RPM repository for Enterprise Linux 7 - x86_64                                                                             457
> remi-safe                                                                                       Safe Remi's RPM repository for Enterprise Linux 7 - x86_64                                                                              5,147
> updates/7/x86_64                                                                                CentOS-7 - Updates                                                                                                                      4,886
> repolist: 50,910
> ```
> 
> from memory we ran
> 
> ```
> yum install https://yum.opensips.org/3.2/releases/el/7/x86_64/opensips-yum-releases-3.2-6.el7.noarch.rpm
> yum install opensips opensips-cli opensips-mysql-module
> ```
> 
> ```
> yum info opensips-mysql-module
> Loaded plugins: langpacks
> Installed Packages
> Name        : opensips-mysql-module
> Arch        : x86_64
> Version     : 3.2.11
> Release     : 1.el7
> Size        : 145 k
> Repo        : installed
> From repo   : opensips
> Summary     : MySQL database connectivity module for OpenSIPS
> URL         : https://opensips.org
> License     : GPLv2+
> Description : OpenSIPS is a very fast and flexible SIP (RFC3261)
>             : server. Written entirely in C, OpenSIPS can handle thousands calls
>             : per second even on low-budget hardware.
>             : .
>             : This package provides the MySQL database driver for OpenSIPS.
> ```

thank you very much ! i found it finally !
