### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by liviuchircu** [OpenSIPS/opensips-cli#18]
Although it is not possible with all modules (e.g. `diagnose`), I would opine that most of them *are* unit testable.  Some examples:

* `user add`
* `database create opensips`
* `database migrate opensips opensips_new`

We should have a unit testing suite for all of these commands, which will speed up the merging of all PRs, prevent regressions such as #16 and make it more fun for developers to confirm their additions and sleep well, knowing they didn't break the whole damn thing! :)

**Comment by yuexiajiayan** [comment]
How to solve this  @problem?@liviuchircu

**Comment by liviuchircu** [comment]
A possible roadmap:

* the test suite uses SQLAlchemy so we can reuse the same command tests over multiple SQL backends
* the test suite runs each time over a fresh testing database, called `"opensips_cli_tests"`
* each test runs a DB command (e.g. `user add`), then double-checks the DB data.
