### ISSUE TITLE
opensips-cli add user does not populate the password column in the database.

### ISSUE THREAD

**Issue by IgnatiusCheng** [OpenSIPS/opensips-cli#24]
opensips-cli add user does not populate the password column in the database.
The SIP client won't register until I manually populate the password column in the subscriber table.

**Comment by razvancrainea** [comment]
@IgnatiusCheng did you try to set the [`plain_text_passwords`](https://github.com/OpenSIPS/opensips-cli/blob/master/docs/modules/user.md#configuration) parameter?

**Comment by IgnatiusCheng** [comment]
By setting plain_text_passwords parameter in the configuration works now.  Thanks.
