### ISSUE TITLE
'database create'  works weirdly with PostgreSQL

### ISSUE THREAD

**Issue by lu-lu-yu** [OpenSIPS/opensips-cli#25]
hi, when working with postgresql, if there's no database 'opensips', using the URL of the SQL database:'postgres://opensips:opensipsrw@127.0.0.1/opensips' reports "fatal error: database 'opensips' doesn't exist", but if there's a database 'opensips' already created, using the URL of the SQL database:'postgres://opensips:opensipsrw@127.0.0.1/opensips' reports "error: database 'opensips' already exists".  Futher more, when there's no database 'opensips', using the URL of the SQL database:'postgres://opensips:opensipsrw@127.0.0.1/**postgres**' turns out no error, but creates the database named 'opensips' and all related tables are created into database 'postgres'. My environment: CentOS6.7, postgres9.6, opensips3.0-stable.

[opensips-cli errors.txt](https://github.com/OpenSIPS/opensips-cli/files/3348160/opensips-cli.errors.txt)

**Comment by Turbid** [comment]
I confirm this problem - tables are created in the template1 base.

debian 10.1, postgresql 11, opensip-cli 0.1~20200128~d37af39-1

**Comment by ryanembregts** [comment]
I am facing the same issue, any update on this?

**Comment by liviuchircu** [comment]
This is now fixed, closing.
