### ISSUE TITLE
default-libmysqlclient-dev  seems to be required in debian9

### ISSUE THREAD

**Issue by gmaruzz** [OpenSIPS/opensips-cli#28]
this maybe must be added to requirements

**Comment by razvancrainea** [comment]
Not sure what's the reason for requesting this. Is it related to `opensips-cli` or `opensips` itself?

**Comment by liviuchircu** [comment]
I think the `pip` build requires `mysql_config`, which is provided by `libmysqlclient-dev`.

**Comment by gmaruzz** [comment]
yeah, probably

but without default-libmysqlclient-dev opensips-cli does not build :)
