### ISSUE TITLE
ERROR: no module 'mi' loaded

### ISSUE THREAD

**Issue by suleil1** [OpenSIPS/opensips-cli#33]
`[root@localhost opensips-cli]# opensips-cli -i 135`
`OpenSIPS CLI for 192.168.2.135 instance`
`(opensips-cli@192.168.2.135): `
`clear     database  diagnose  exit      help      history   instance  quit      set       tls       trace     trap      user `
`(opensips-cli@192.168.2.135): mi`
`ERROR: no module 'mi' loaded`

Why there is no module 'mi'?
I followed the procedure exactly.

**Comment by suleil1** [comment]
I found that there was 'mi' without specifying the instance, and once I switched the instance, 'mi' disappeared

**Comment by razvancrainea** [comment]
most likely the 135 instance cannot connect to the `mi` endpoint, that's why `mi` module is not available.

**Comment by liviuchircu** [comment]
@suleil1 Each instance will inherit the `[default]` `communication_type`.  So, for example, in the following `~/.opensips-cli.cfg`:

```
[default]
log_level: INFO
prompt_name: opensips-cli
prompt_intro: Welcome to OpenSIPS Command Line Interface!
prompt_emptyline_repeat_cmd: False
history_file: ~/.opensips-cli.history
history_file_size: 1000
output_type: pretty-print

#communication_type: http
#url: http://127.0.0.1:8888/mi

communication_type: http
#url: http://127.0.0.1:8888/mi

[1]
prompt_name: opensips-cli-1
```

... instance `-i 1` will actually try to connect to `127.0.0.1:8888`, and NOT to the `/tmp/opensips_fifo` file!  Be sure to explicitly specify `communication_type: fifo` (for example) for each instance as well.

Closing for now.
