### ISSUE TITLE
Add ability to create user

### ISSUE THREAD

**Issue by sdwru** [OpenSIPS/opensips-cli#39]
`/usr/sbin/opensipsdbctl create` asked for the root password and then created `opensips` user with all the proper DB permissions.  It appears `opensips-cli -x database create` does not duplicate that behavior, requiring me to create the `opensips` DB user and permissions manually.  Using root user is not a good idea so it would be nice if the previous behavior were duplicated.

**Comment by liviuchircu** [comment]
Duplicate of #20, closing here.  Coming up with a "behind-the-curtains" solution for this problem is now on the top my TODO list.
