### ISSUE TITLE
config file doesn't take effect

### ISSUE THREAD

**Issue by AlexYe233** [OpenSIPS/opensips-cli#45]
Hi,I'm using opensips3.0.2 and OpenSIPS CLI 0.1.0 with mysql8.0.19-0ubuntu0.19.10.3
and I have config file in /etc/opensips/opensips.cfg,but config file seems take no effect.
when I run" opensips-cli -x user add user@domain password"
it still require the URL of the database and try to insert into the default database"opensips" instead of the database in the config file,thus cause the err"Access denied for user 'opensips'@'localhost' to database 'opensips'.

**Comment by razvancrainea** [comment]
There is a problem with the name of the parameter that is read for the `database_url`. I am soon pushing a fix for this.
