### ISSUE TITLE
ERROR: failed to connect to DB as root, please provide or fix the 'database_admin_url'

### ISSUE THREAD

**Issue by lesvere** [OpenSIPS/opensips-cli#52]
pyhton3.4 install cli tools.
1. run opensips-cli -f /usr/local/etc/opensips/opensips-cli.cfg
2. database create 
    then input my root password: root.
It always return: 

>  #### ERROR:`` failed to connect to DB as root, please provide or fix the 'database_admin_url'

### This my fully opensips-cli.cfg content:

[default]
database_modules: dialog usrloc
[mysql]
database_admin_url: mysql://root@192.168.7.242:3306/opensips

**Comment by liviuchircu** [comment]
Thank you for the report, @lesvere! First, please make sure access works using the console:

```
mysql -uroot -p<password> -h192.168.7.242
```

I suspect you have only granted access for `-hlocalhost` or `-h127.0.0.1`, hence why login to the IP address isn't working.

**Comment by lesvere** [comment]
Thans for your reply.

Before I had depoly opensips on base system, and depoly oensips-cp on docker.

Now, I had resolved that problem!

But i have other problem, this is link: https://github.com/OpenSIPS/opensips-cli/issues/54
