### ISSUE TITLE
[BUG] Fifo location 

### ISSUE THREAD

**Issue by volga629** [OpenSIPS/opensips-cli#6]
Some commands are not honor fifo location file

```
[root@hostname ~]# opensips-cli 
Welcome to OpenSIPS Command Line Interface!
(opensips-cli): diagnose 
ERROR: communication exception for 'get_statistics' returned: fifo file /tmp/opensips_fifo does not exist!
ERROR: Is OpenSIPS running?
(opensips-cli): exit
[root@hostname ~]# cat /etc/opensips-cli/opensips-cli.cfg 
[default]
log_level: WARNING
prompt_name: opensips-cli
prompt_intro: Welcome to OpenSIPS Command Line Interface!
prompt_emptyline_repeat_cmd: False
history_file: ~/.opensips-cli.history
history_file_size: 1000
output_type: pretty-print
communication_type: fifo
fifo_file: /var/run/opensips/opensips_fifo
[root@hostname ~]# 
```

**Comment by liviuchircu** [comment]
Hey, @volga629 !

Your `/etc/opensips-cli/opensips-cli.cfg` is a non-standard path, so the cli will simply fall back to its built-in default for the fifo path: `/tmp/opensips_fifo`.  So either move it into a standard location, or use the `-i` switch to specify it when launching the CLI.

As per the [docs](https://github.com/OpenSIPS/opensips-cli#configuration), the standard paths are, in decreasing priority order:

* `~/.opensips-cli.cfg`
* `/etc/opensips-cli.cfg`
* `/etc/opensips/opensips-cli.cfg`

**Comment by volga629** [comment]
Thank you for reply,
Yes that correct, but if opensips-cli installed outside of opensips  installation.
Example to manipulate multiply instances in cluster.
I think it should not rely on opensips folder structure.

**Comment by razvancrainea** [comment]
Hi, @volga629!

If `opensips-cli` is installed outside of opensips installation, simply use the other two versions, which have higher priority anyway and are not depend on the `/etc/opensips` directory. So I wouldn't say it relies on the `opensips` structure, it just uses it if it is there and no other files are specified.

Best regards,
Răzvan
