### ISSUE TITLE
Install on debian/ubuntu

### ISSUE THREAD

**Issue by vasilakisfil** [OpenSIPS/opensips-cli#62]
I followed the instructions in the Installation section, but the instructions never say how to install the actual tool through a .deb package, only its dependencies. Am I missing something ?

**Comment by liviuchircu** [comment]
hey, @vasilakisfil - you are right.  The installation section needs to be updated with some links to the [`opensips-cli` DEBs](https://apt.opensips.org/packages.php?v=cli) (managed and hosted by the benevolent @nikbyte)

**Comment by liviuchircu** [comment]
Thank you for the report @vasilakisfil - the install instructions should be a lot more helpful now :)
