### ISSUE TITLE
SIP Trunk - functionality (table registrant)

### ISSUE THREAD

**Issue by rzerres** [OpenSIPS/opensips-cli#8]
since version v3.0.0 the admin tool opensipsctl is depreciated, there are quite some functional aspects that need to be adopted to opensips-cli.

SIP-Trunking is quite commen nowadays and registration of the SIP-Server to the  PSTN-SIP provider is a must. opensipsctl could handle uac_registrant and I kindly request to get that functionaltiy on par with opensips-cli.

**Comment by bogdan-iancu** [comment]
@rzerres , the current policy is to try as much as possible to push the provisioning support into [OpenSIPS Control Panel](http://controlpanel.opensips.org/) and not into the opensips-cli.
But I agree that currently there is no provisioning support for uac_registrant (neither in CLI, nor in CP) :( .

**Comment by rzerres** [comment]
@bogdan-iancu 
well, I'm willing to get into improvement. Either CLI or Web-Gui. Are you guys willing to discuss the further proceeding on the freenode #opensips channel? That might speed up the neccessary synchronization.
For our own company we need a working SIP-Trunk connection to German Telekom. And i like to make it work with pure 3.0.0 release. What would be a good time/date?
Ralf

**Comment by bogdan-iancu** [comment]
@rzerres , we can use the slack channel of OpenSIPS too :) . 
For the CP (web), it will be quite easy to add this new tool , still we need to create the new CP version for 3.0 (we might have some incompatibilities at MI level between the current CP and 3.0).

**Comment by rzerres** [comment]
@bogdan-iancu, didn't know that the slack channel exists. Whatever is more appropriate. 
Todoy I forked opensips-cp. Yesterday i started to create a "SIP Trunk" system entry. I try to reuse the code found in RTPProxy and take it as reference.
First forms are ready. One question arises very soon: How to handle input validation? I have seen, you are using classes. Does the environment already reusable validation code?

**Comment by rzerres** [comment]
@bogdan-iancu 
how to connect to opensips slack?

**Comment by bogdan-iancu** [comment]
drop me a private email on bogdan at opensips dot org

**Comment by rzerres** [comment]
i implemented the needed code in opensips-cp. A PR is uploaded.
