### ISSUE TITLE
The installation from apt is not running

### ISSUE THREAD

**Issue by flaviogoncalves** [OpenSIPS/opensips-cli#80]
I'm having two issues installing opensips-cli from packages. 

First the keyserver is returning route not found. 

apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 049AD65B
Executing: /tmp/apt-key-gpghome.DMqN5tfR45/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 049AD65B
gpg: keyserver receive failed: No route to host

After changing the server I got to circunvent this one. 
root@debian:/home/opensips# apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 049AD65B
Executing: /tmp/apt-key-gpghome.Ncc2wPBXpK/gpg.1.sh --keyserver hkp://pool.sks-keyservers.net --recv-keys 049AD65B
gpg: key 81CE21E7049AD65B: public key "OpenSIPS Project <info@opensips.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1

apt update

apt install opensips-cli

All packages are up to date.
W: Skipping acquire of configured file 'cli-nightly/binary-amd64/Packages' as repository 'https://apt.opensips.org buster InRelease' doesn't have the component 'cli-nightly' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'cli-nightly/i18n/Translation-en_US' as repository 'https://apt.opensips.org buster InRelease' doesn't have the component 'cli-nightly' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'cli-nightly/i18n/Translation-en' as repository 'https://apt.opensips.org buster InRelease' doesn't have the component 'cli-nightly' (component misspelt in sources.list?)

I browsed the repository and opensips-cli does not seem to be there. 

OpenSIPS installs normally

**Comment by liviuchircu** [comment]
Hi, @flaviogoncalves!

This may be related to last night's build which failed because the new `wolfssl` module requires more complex `git submodule update` commands which are still on the TODO list.

This exact `opensips-cli` repository worked for me just 1 week ago on Debian 10, so it's just a matter of time before it's up again.

**Comment by varghesepaul** [comment]
Thanks @liviuchircu for looking into this. We are also facing the same issue.

**Comment by nikbyte** [comment]
@flaviogoncalves 

no route is your local error.

```
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 049AD65B
Executing: /tmp/apt-key-gpghome.kskORZgzKf/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 049AD65B
gpg: key 81CE21E7049AD65B: public key "OpenSIPS Project <info@opensips.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

about build I'll report here soon.

**Comment by flaviogoncalves** [comment]
Hi Nick I got both errors, the no route first. I changed the key server  to hkp://pool.sks-keyservers.net  apt-get update worked but the repository was not found.  I tried to manually find the package but it does not seem to be there. 

Skipping acquire of configured file 'cli-nightly/binary-amd64/Packages' as repository 'https://apt.opensips.org buster InRelease' doesn't have the component 'cli-nightly' (component misspelt in sources.list?)

**Comment by nikbyte** [comment]
@flaviogoncalves I only wanted to say that "no route" is your local issue.
cli-nightly repository is a different issue.

**Comment by nikbyte** [comment]
The repository fixed.

**Comment by flaviogoncalves** [comment]
Thank you @nikbyte,
