### ISSUE TITLE
rpm repository broken

### ISSUE THREAD

**Issue by luminblade** [OpenSIPS/opensips-cli#84]
I'm currently unable to install opensips-cli from the yum repository (CentOS 7.x)

opensips-cli-0.1.20210415.3221 FAILED
https://yum.opensips.org/cli/nightly/el/7/noarch/opensips-cli-0.1.20210415.3221fbd-1.el7.noarch.rpm: [Errno 14] HTTPS Error 404 - Not Found

**Comment by nikbyte** [comment]
Fixed.
