### ISSUE TITLE
How to use opensips-cli using db-text?

### ISSUE THREAD

**Issue by Otoru** [OpenSIPS/opensips-cli#88]
For projects where the change I have not foreseen recurring changes (for example a proxy we only use for dispatcher and nat traversal) I like to work with text-db as it is one less component to monitor and maintain.
However, I have not found any documentation on how to use opensips-cli to create the tables using text-db.

**Comment by gallonyin** [comment]
i found it here https://www.opensips.org/Documentation/Install-DBDeployment-3-2#toc2

#Note: OpenSIPS CLI searches for its configuration files in ~/.opensips-cli.cfg, /etc/opensips-cli.cfg, /etc/opensips/opensips-cli.cfg, but you can also specify your own configuration file using the -f parameter.

**Comment by razvancrainea** [comment]
Unfortunately `opensips-cli` no longer supports db-text. It does, however, support sqlite, so if you prefer using DB files, you can try to migrate your setup to sqlite.
