### ISSUE TITLE
how to install 'yum install opensips-db_mysql '?

### ISSUE THREAD

**Issue by honyyang** [OpenSIPS/opensips-cli#89]
where is the 'opensips-db_mysql ' rpm?

**Comment by razvancrainea** [comment]
You are probably asking about the opensips mysql yum package, which has been renamed to `opensips-mysql-module`.

PS: this has nothing to do with the `opensips-cli` project, it is related to the `opensips` project - next time, please choose the proper package to avoid any confusion on our side.
