### ISSUE TITLE
Installation from apt is not working

### ISSUE THREAD

**Issue by varghesepaul** [OpenSIPS/opensips-cli#90]
Repo Details:

> apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 049AD65B
>echo "deb https://apt.opensips.org buster cli-nightly" >/etc/apt/sources.list.d/opensips-cli.list

Error: 
#15 9.540 E: Failed to fetch https://apt.opensips.org/pool/buster/cli-nightly/o/opensips-cli/opensips-cli_0.1~20211116~696114a-1_all.deb  404  Not Found [IP: 176.9.203.99 443]

I checked the repository and opensips-cli does not seem to be there. 

Can you please check?

**Comment by razvancrainea** [comment]
Not sure what was going on, but it seems to be OK now.
