### ISSUE TITLE
Can't install opensips-cli

### ISSUE THREAD

**Issue by fdmgit** [OpenSIPS/opensips-cli#95]
I have setup a new server:

Ubuntu 22.04
Python: 3.10.4

When I try to install opensips-cli

apt install opensips-cli

I get the following error:

The following packages have unmet dependencies:
 opensips-cli : Depends: python but it is not installable
E: Unable to correct problems, you have held broken packages.

Any hints ?

**Comment by iliesh** [comment]
I have the same issue, any update?

**Comment by SonicJoe** [comment]
I'm seeing the same issue. I tried installing every python package I could find, but still no improvement.

**Comment by liviuchircu** [comment]
Hi, all!  I managed to reproduce the issue and just pushed a fix for it (https://github.com/OpenSIPS/opensips-cli/commit/a3e0c7d91a).  Let's re-check installing the CLI via APT repo tomorrow, after the packages get rebuilt.
