### ISSUE TITLE
Empty password value when creating users

### ISSUE THREAD

**Issue by babakyakhchali** [OpenSIPS/opensips-cli#97]
Hi
Trying to create a user like this:
opensips-cli -x user add 1000@example.com 123456
user is created successfully but registration fails, after checking subscribers table I see password column is empty. I set it using sql and everything works
opensips-cli version: 0.1~20220516~2dff522-1

**Comment by liviuchircu** [comment]
Hi, please check your `plain_text_passwords` setting, which is by default set to `False`.  Most likely, the `opensips-cli` is populating the hash fields of your table, leaving the "password" column empty.

While this is the preferred, secure way of running a production installation of OpenSIPS, for testing purposes it is fine to enable `plain_text_passwords` and store anything you want in that table :)
